### ISSUE TITLE
Add `last_modified` filter and multi-filter combinations

### ISSUE THREAD

**Issue by bettjesse** [bettjesse/FileSentry#1]
### Add `last_modified` Filter and Multi-Filter Combinations

**Requested by**: (https://www.reddit.com/r/selfhosted/comments/1j5ih0w/a_selfhosted_yamlconfigurable_file_watcher/)  
**Goal**: Allow users to filter files by modification time and combine multiple filter conditions using AND/OR logic.

---

#### 1. Last Modified Filter
```yaml
filters:
  - last_modified: ">7d"   # Files older than 7 days
  - last_modified: "<=24h"  # Files modified in last 24 hours
Technical Requirements:

Use Go's os.FileInfo.ModTime() to check file modification time

Support operators: >, <, >=, <=, ==

Parse duration suffixes: d (days), h (hours), m (minutes)

Handle both relative times (like "24h") and absolute timestamps (future expansion)
```

### 2. Filter Combinations

```
# AND combination (all filters must match)
filters:
  all_of:
    - extension: [".jpg", ".png"]
    - last_modified: ">30d"

# OR combination (any filter matches)
filters:
  any_of:
    - extension: ".pdf"
    - last_modified: "<1h"
```
Tasks Checklist
Add last_modified filter parsing logic

Implement duration parser supporting d/h/m suffixes

Create filter combinator logic (all_of/any_of)

Update YAML configuration parser

Add unit tests for new filters

Document features in README.md

Create example configurations
