### ISSUE TITLE
Users need to automatically rename/organize torrents after download.

### ISSUE THREAD

**Issue by applesoff** [bettjesse/FileSentry#2]
I have torrents from an RSS feed get added to my files every so often and it is an annoying step to rename them all and move them to the correct directories. can this program rename them after they finish downloading? i want to remove parentheses and the words therein for the file and their directories.

**Comment by bettjesse** [comment]
**Proposed Solution**  
1. Regex-based renaming (remove `(1080p)`, `[Group]` etc)  
2. Smart directory creation (`/media/{show}/Season {num}/`)  
3. Download completion detection  

**Config Example**  
```yaml  
rules:  
  - name: "Clean Torrents"  
    conditions:  
      path: "/downloads/torrents/*"  
    actions:  
      rename:  
        pattern: "\(.*?\)"  
        replacement: ""  
      move:  
        target: "/media/{series}/Season {season}/"  
```

Next Steps

Add regex support to rename action

Implement torrent-complete detection

Add filename pattern variables
